### PR TITLE
Compiles with ESP8266-2.5.0 and ArduinoJSON 6

### PR DESCRIPTION
**Pull request by miaoski**
Hi.
I got several compilation errors when trying to compile the original code with Arduino 1.8.7, ESP8266 core library 2.5.0 and ArduinoJSON 6 (if you happen to upgrade the libraries like me).
The PR solves the compilation errors.
Thanks.

### CODE REVIEW

**Comment by miaoski** [comment]
One more file has to be changed.  I'm closing this one and make another PR.
