### PR TITLE
Compiles with ESP8266-2.5.0 and ArduinoJSON 6

### PR DESCRIPTION
**Pull request by miaoski**
Hi.
I got several compilation errors when trying to compile the original code with Arduino 1.8.7, ESP8266 core library 2.5.0 and ArduinoJSON 6 (if you happen to upgrade the libraries like me).
The PR solves the compilation errors.
Thanks.

### CODE REVIEW

**Comment by platenspeler** [comment]
Thanks, I corrected the typos. What is the advantage to change to Jaon6?

**Comment by platenspeler** [comment]
OK, I changed the code to make use of ArduinoJSON6. I do not know if it helps to execute the pull request, but I will do. I hope everybody sees the new format. I will release a new version shortly and incorporate these changes also.
